name: PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          cache: gradle
      - name: Build, test, coverage
        run: ./gradlew build
