name: Publish SDK

on:
  # either if we push a tag manually or if it's called from create-release workflow
  push:
    tags:
      - 'v*'
  workflow_call:

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # make sure you have full history and tags
      - name: Checkout tag if available
        run: |
          TAG=$(git tag --points-at HEAD)
          if [ -n "$TAG" ]; then
            echo "Tag found: $TAG. Checking out tag..."
            git checkout "$TAG"
          else
            echo "No tag found on this commit."
          fi
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - uses: burrunan/gradle-cache-action@v1
        name: Deploy Release to Maven central
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassphrase: ${{ secrets.GPG_PASSPHRASE }}
        with:
          job-id: release
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
      - name: Create Github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
